[database]
db_host="localhost"
database="cms"
db_driver="pdo_mysql"
user=""
password=""
table_prefix="cms_"

[URL]
protocol="http"
port="80"

[email]
; obligatoires pour que ça fonctionne
smtp_host="smtp.service.de.messagerie"
smtp_username="adresse@email"
smtp_password=""
; choisir "tls" (smarttls) ou "ssl" (smtps) ou "plain_text"/chaine vide
smtp_secure="tls"
email_dest="adresse@email"

; optionnels
; renseigner email_from pour montrer au destinataire une adresse différente de celle réellement utilisée pour lui éviter de "répondre au site web"
email_from=""
email_from_name="site web"
email_dest_name="moi"