[database]
db_host="localhost"
database="cms"
db_driver="pdo_mysql"
user=""
password=""
table_prefix="cms_"

[URL]
protocol="http"
port="80"

[email]
smtp_host="smtp.service.de.messagerie"
smtp_username="adresse@email"
smtp_password=""
; choisir "tls" (smarttls) ou "ssl" (smtps) ou "plain_text"/chaine vide
smtp_secure="tls"
email_from=""
email_from_name=""
email_dest="adresse@email"
email_dest_name=""